exclude = [
    "data/generator/generator.py",
    "data/samples/scrubbed_RES_capture.pcapng",
    "data/samples/tcp_packet.pcap",
    "data/samples/udp_packet.pcap",
    "data/sanity_check.py",
    "data/scrubber.py",
    "requirements.txt",
    "*.py",
    "requirements.txt",
    "./requirements.txt",
    ".ignore",
    ".gitignore",
    "*.json", # Cannot exclude .cargo_vcs_info.json, .rutc_info.json etc
    ".cargo_vcs_info.json", # Cannot exclude .cargo_vcs_info.json
    ".github/",
    "data",
    "data/*",
    "data/**",
    "CHANGELOG.md",
]